<a href="https://colab.research.google.com/github/vishalmahor886/basic_ML_code/blob/main/iterative_imputer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
url = 'https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day40-iterative-imputer/50_Startups.csv'
df = pd.read_csv(url, usecols=['R&D Spend','Administration','Marketing Spend','Profit'])

In [ ]:
df = df/10000

In [ ]:
df.sample(5)

    R&D Spend  Administration  Marketing Spend     Profit
10  10.191308       11.059411        22.916095  14.612195
40   2.875433       11.854605        17.279567   7.823991
1   16.259770       15.137759        44.389853  19.179206
30   6.199448       11.564128         9.113124   9.993759
46   0.131546       11.581621        29.711446   4.949075

In [ ]:
df.isnull().mean()*100

R&D Spend          0.0
Administration     0.0
Marketing Spend    0.0
Profit             0.0
dtype: float64

In [ ]:
df = df.iloc[:,0:-1]
df

    R&D Spend  Administration  Marketing Spend
0   16.534920       13.689780        47.178410
1   16.259770       15.137759        44.389853
2   15.344151       10.114555        40.793454
3   14.437241       11.867185        38.319962
4   14.210734        9.139177        36.616842
5   13.187690        9.981471        36.286136
6   13.461546       14.719887        12.771682
7   13.029813       14.553006        32.387668
8   12.054252       14.871895        31.161329
9   12.333488       10.867917        30.498162
10  10.191308       11.059411        22.916095
11  10.067196        9.179061        24.974455
12   9.386375       12.732038        24.983944
13   9.199239       13.549507        25.266493
14  11.994324       15.654742        25.651292
15  11.452361       12.261684        26.177623
16   7.801311       12.159755        26.434606
17   9.465716       14.507758        28.257431
18   9.174916       11.417579        29.491957
19   8.641970       15.351411         0.000000
20   7.625386       11.386730        29.866447
21   7.838947       15.377343        29.973729
22   7.399456       12.278275        30.331926
23   6.753253       10.575103        30.476873
24   7.704401        9.928134        14.057481
25   6.466471       13.955316        13.796262
26   7.532887       14.413598        13.405007
27   7.210760       12.786455        35.318381
28   6.605152       18.264556        11.814820
29   6.560548       15.303206        10.713838
30   6.199448       11.564128         9.113124
31   6.113638       15.270192         8.821823
32   6.340886       12.921961         4.608525
33   5.549395       10.305749        21.463481
34   4.642607       15.769392        21.079767
35   4.601402        8.504744        20.551764
36   2.866376       12.705621        20.112682
37   4.406995        5.128314        19.702942
38   2.022959        6.594793        18.526510
39   3.855851        8.298209        17.499930
40   2.875433       11.854605        17.279567
41   2.789292        8.471077        16.447071
42   2.364093        9.618963        14.800111
43   1.550573       12.738230         3.553417
44   2.217774       15.480614         2.833472
45   0.100023       12.415304         0.190393
46   0.131546       11.581621        29.711446
47   0.000000       13.542692         0.000000
48   0.054205        5.174315         0.000000
49   0.000000       11.698380         4.517306

In [ ]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[-1,-1] = np.nan

In [ ]:
df.isnull().mean()*100

R&D Spend          2.0
Administration     2.0
Marketing Spend    2.0
dtype: float64

In [ ]:
df.sample(5)

    R&D Spend  Administration  Marketing Spend
13   9.199239       13.549507        25.266493
44   2.217774       15.480614         2.833472
16   7.801311       12.159755        26.434606
7   13.029813       14.553006        32.387668
39   3.855851        8.298209        17.499930

In [ ]:
# Step 1 - Impute all missing values with mean of respective col

df0 = pd.DataFrame()

df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())

In [ ]:
# 0th Iteration
df0

    R&D Spend  Administration  Marketing Spend
0   16.534920       13.689780        47.178410
1    7.190782       15.137759        44.389853
2   15.344151       10.114555        40.793454
3   14.437241       12.139919        38.319962
4   14.210734        9.139177        36.616842
5   13.187690        9.981471        36.286136
6   13.461546       14.719887        12.771682
7   13.029813       14.553006        32.387668
8   12.054252       14.871895        31.161329
9   12.333488       10.867917        30.498162
10  10.191308       11.059411        22.916095
11  10.067196        9.179061        24.974455
12   9.386375       12.732038        24.983944
13   9.199239       13.549507        25.266493
14  11.994324       15.654742        25.651292
15  11.452361       12.261684        26.177623
16   7.801311       12.159755        26.434606
17   9.465716       14.507758        28.257431
18   9.174916       11.417579        29.491957
19   8.641970       15.351411         0.000000
20   7.625386       11.386730        29.866447
21   7.838947       15.377343        29.973729
22   7.399456       12.278275        30.331926
23   6.753253       10.575103        30.476873
24   7.704401        9.928134        14.057481
25   6.466471       13.955316        13.796262
26   7.532887       14.413598        13.405007
27   7.210760       12.786455        35.318381
28   6.605152       18.264556        11.814820
29   6.560548       15.303206        10.713838
30   6.199448       11.564128         9.113124
31   6.113638       15.270192         8.821823
32   6.340886       12.921961         4.608525
33   5.549395       10.305749        21.463481
34   4.642607       15.769392        21.079767
35   4.601402        8.504744        20.551764
36   2.866376       12.705621        20.112682
37   4.406995        5.128314        19.702942
38   2.022959        6.594793        18.526510
39   3.855851        8.298209        17.499930
40   2.875433       11.854605        17.279567
41   2.789292        8.471077        16.447071
42   2.364093        9.618963        14.800111
43   1.550573       12.738230         3.553417
44   2.217774       15.480614         2.833472
45   0.100023       12.415304         0.190393
46   0.131546       11.581621        29.711446
47   0.000000       13.542692         0.000000
48   0.054205        5.174315         0.000000
49   0.000000       11.698380        21.440983

In [ ]:
# Remove the col1 imputed value
df1 = df0.copy()

df1.iloc[1,0] = np.nan

df1

    R&D Spend  Administration  Marketing Spend
0   16.534920       13.689780        47.178410
1         NaN       15.137759        44.389853
2   15.344151       10.114555        40.793454
3   14.437241       12.139919        38.319962
4   14.210734        9.139177        36.616842
5   13.187690        9.981471        36.286136
6   13.461546       14.719887        12.771682
7   13.029813       14.553006        32.387668
8   12.054252       14.871895        31.161329
9   12.333488       10.867917        30.498162
10  10.191308       11.059411        22.916095
11  10.067196        9.179061        24.974455
12   9.386375       12.732038        24.983944
13   9.199239       13.549507        25.266493
14  11.994324       15.654742        25.651292
15  11.452361       12.261684        26.177623
16   7.801311       12.159755        26.434606
17   9.465716       14.507758        28.257431
18   9.174916       11.417579        29.491957
19   8.641970       15.351411         0.000000
20   7.625386       11.386730        29.866447
21   7.838947       15.377343        29.973729
22   7.399456       12.278275        30.331926
23   6.753253       10.575103        30.476873
24   7.704401        9.928134        14.057481
25   6.466471       13.955316        13.796262
26   7.532887       14.413598        13.405007
27   7.210760       12.786455        35.318381
28   6.605152       18.264556        11.814820
29   6.560548       15.303206        10.713838
30   6.199448       11.564128         9.113124
31   6.113638       15.270192         8.821823
32   6.340886       12.921961         4.608525
33   5.549395       10.305749        21.463481
34   4.642607       15.769392        21.079767
35   4.601402        8.504744        20.551764
36   2.866376       12.705621        20.112682
37   4.406995        5.128314        19.702942
38   2.022959        6.594793        18.526510
39   3.855851        8.298209        17.499930
40   2.875433       11.854605        17.279567
41   2.789292        8.471077        16.447071
42   2.364093        9.618963        14.800111
43   1.550573       12.738230         3.553417
44   2.217774       15.480614         2.833472
45   0.100023       12.415304         0.190393
46   0.131546       11.581621        29.711446
47   0.000000       13.542692         0.000000
48   0.054205        5.174315         0.000000
49   0.000000       11.698380        21.440983

In [ ]:
# Use first 3 rows to build a model and use the last for prediction

X = df1.iloc[[0,2,3,4],1:3]
X

   Administration  Marketing Spend
0       13.689780        47.178410
2       10.114555        40.793454
3       12.139919        38.319962
4        9.139177        36.616842

In [ ]:
y = df1.iloc[[0,2,3,4],0]
y

0    16.534920
2    15.344151
3    14.437241
4    14.210734
Name: R&D Spend, dtype: float64

In [ ]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[1,1:].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([15.68665427])

In [ ]:
df1.iloc[1,0] = 15.68

In [ ]:
df1

    R&D Spend  Administration  Marketing Spend
0   16.534920       13.689780        47.178410
1   15.680000       15.137759        44.389853
2   15.344151       10.114555        40.793454
3   14.437241       12.139919        38.319962
4   14.210734        9.139177        36.616842
5   13.187690        9.981471        36.286136
6   13.461546       14.719887        12.771682
7   13.029813       14.553006        32.387668
8   12.054252       14.871895        31.161329
9   12.333488       10.867917        30.498162
10  10.191308       11.059411        22.916095
11  10.067196        9.179061        24.974455
12   9.386375       12.732038        24.983944
13   9.199239       13.549507        25.266493
14  11.994324       15.654742        25.651292
15  11.452361       12.261684        26.177623
16   7.801311       12.159755        26.434606
17   9.465716       14.507758        28.257431
18   9.174916       11.417579        29.491957
19   8.641970       15.351411         0.000000
20   7.625386       11.386730        29.866447
21   7.838947       15.377343        29.973729
22   7.399456       12.278275        30.331926
23   6.753253       10.575103        30.476873
24   7.704401        9.928134        14.057481
25   6.466471       13.955316        13.796262
26   7.532887       14.413598        13.405007
27   7.210760       12.786455        35.318381
28   6.605152       18.264556        11.814820
29   6.560548       15.303206        10.713838
30   6.199448       11.564128         9.113124
31   6.113638       15.270192         8.821823
32   6.340886       12.921961         4.608525
33   5.549395       10.305749        21.463481
34   4.642607       15.769392        21.079767
35   4.601402        8.504744        20.551764
36   2.866376       12.705621        20.112682
37   4.406995        5.128314        19.702942
38   2.022959        6.594793        18.526510
39   3.855851        8.298209        17.499930
40   2.875433       11.854605        17.279567
41   2.789292        8.471077        16.447071
42   2.364093        9.618963        14.800111
43   1.550573       12.738230         3.553417
44   2.217774       15.480614         2.833472
45   0.100023       12.415304         0.190393
46   0.131546       11.581621        29.711446
47   0.000000       13.542692         0.000000
48   0.054205        5.174315         0.000000
49   0.000000       11.698380        21.440983

In [ ]:
# Remove the col2 imputed value

df1.iloc[3,1] = np.nan

df1

    R&D Spend  Administration  Marketing Spend
0   16.534920       13.689780        47.178410
1   15.680000       15.137759        44.389853
2   15.344151       10.114555        40.793454
3   14.437241             NaN        38.319962
4   14.210734        9.139177        36.616842
5   13.187690        9.981471        36.286136
6   13.461546       14.719887        12.771682
7   13.029813       14.553006        32.387668
8   12.054252       14.871895        31.161329
9   12.333488       10.867917        30.498162
10  10.191308       11.059411        22.916095
11  10.067196        9.179061        24.974455
12   9.386375       12.732038        24.983944
13   9.199239       13.549507        25.266493
14  11.994324       15.654742        25.651292
15  11.452361       12.261684        26.177623
16   7.801311       12.159755        26.434606
17   9.465716       14.507758        28.257431
18   9.174916       11.417579        29.491957
19   8.641970       15.351411         0.000000
20   7.625386       11.386730        29.866447
21   7.838947       15.377343        29.973729
22   7.399456       12.278275        30.331926
23   6.753253       10.575103        30.476873
24   7.704401        9.928134        14.057481
25   6.466471       13.955316        13.796262
26   7.532887       14.413598        13.405007
27   7.210760       12.786455        35.318381
28   6.605152       18.264556        11.814820
29   6.560548       15.303206        10.713838
30   6.199448       11.564128         9.113124
31   6.113638       15.270192         8.821823
32   6.340886       12.921961         4.608525
33   5.549395       10.305749        21.463481
34   4.642607       15.769392        21.079767
35   4.601402        8.504744        20.551764
36   2.866376       12.705621        20.112682
37   4.406995        5.128314        19.702942
38   2.022959        6.594793        18.526510
39   3.855851        8.298209        17.499930
40   2.875433       11.854605        17.279567
41   2.789292        8.471077        16.447071
42   2.364093        9.618963        14.800111
43   1.550573       12.738230         3.553417
44   2.217774       15.480614         2.833472
45   0.100023       12.415304         0.190393
46   0.131546       11.581621        29.711446
47   0.000000       13.542692         0.000000
48   0.054205        5.174315         0.000000
49   0.000000       11.698380        21.440983

In [ ]:
# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[[0,1,2,4],[0,2]]
X

   R&D Spend  Marketing Spend
0  16.534920        47.178410
1  15.680000        44.389853
2  15.344151        40.793454
4  14.210734        36.616842

In [ ]:
y = df1.iloc[[0,1,2,4],1]
y

0    13.689780
1    15.137759
2    10.114555
4     9.139177
Name: Administration, dtype: float64

In [ ]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([11.38062788])

In [ ]:
df1.iloc[3,1] = 11.38

In [ ]:
df1

    R&D Spend  Administration  Marketing Spend
0   16.534920       13.689780        47.178410
1   15.680000       15.137759        44.389853
2   15.344151       10.114555        40.793454
3   14.437241       11.380000        38.319962
4   14.210734        9.139177        36.616842
5   13.187690        9.981471        36.286136
6   13.461546       14.719887        12.771682
7   13.029813       14.553006        32.387668
8   12.054252       14.871895        31.161329
9   12.333488       10.867917        30.498162
10  10.191308       11.059411        22.916095
11  10.067196        9.179061        24.974455
12   9.386375       12.732038        24.983944
13   9.199239       13.549507        25.266493
14  11.994324       15.654742        25.651292
15  11.452361       12.261684        26.177623
16   7.801311       12.159755        26.434606
17   9.465716       14.507758        28.257431
18   9.174916       11.417579        29.491957
19   8.641970       15.351411         0.000000
20   7.625386       11.386730        29.866447
21   7.838947       15.377343        29.973729
22   7.399456       12.278275        30.331926
23   6.753253       10.575103        30.476873
24   7.704401        9.928134        14.057481
25   6.466471       13.955316        13.796262
26   7.532887       14.413598        13.405007
27   7.210760       12.786455        35.318381
28   6.605152       18.264556        11.814820
29   6.560548       15.303206        10.713838
30   6.199448       11.564128         9.113124
31   6.113638       15.270192         8.821823
32   6.340886       12.921961         4.608525
33   5.549395       10.305749        21.463481
34   4.642607       15.769392        21.079767
35   4.601402        8.504744        20.551764
36   2.866376       12.705621        20.112682
37   4.406995        5.128314        19.702942
38   2.022959        6.594793        18.526510
39   3.855851        8.298209        17.499930
40   2.875433       11.854605        17.279567
41   2.789292        8.471077        16.447071
42   2.364093        9.618963        14.800111
43   1.550573       12.738230         3.553417
44   2.217774       15.480614         2.833472
45   0.100023       12.415304         0.190393
46   0.131546       11.581621        29.711446
47   0.000000       13.542692         0.000000
48   0.054205        5.174315         0.000000
49   0.000000       11.698380        21.440983

In [ ]:
# Remove the col3 imputed value
df1.iloc[4,-1] = np.nan

df1

    R&D Spend  Administration  Marketing Spend
0   16.534920       13.689780        47.178410
1   15.680000       15.137759        44.389853
2   15.344151       10.114555        40.793454
3   14.437241       11.380000        38.319962
4   14.210734        9.139177              NaN
5   13.187690        9.981471        36.286136
6   13.461546       14.719887        12.771682
7   13.029813       14.553006        32.387668
8   12.054252       14.871895        31.161329
9   12.333488       10.867917        30.498162
10  10.191308       11.059411        22.916095
11  10.067196        9.179061        24.974455
12   9.386375       12.732038        24.983944
13   9.199239       13.549507        25.266493
14  11.994324       15.654742        25.651292
15  11.452361       12.261684        26.177623
16   7.801311       12.159755        26.434606
17   9.465716       14.507758        28.257431
18   9.174916       11.417579        29.491957
19   8.641970       15.351411         0.000000
20   7.625386       11.386730        29.866447
21   7.838947       15.377343        29.973729
22   7.399456       12.278275        30.331926
23   6.753253       10.575103        30.476873
24   7.704401        9.928134        14.057481
25   6.466471       13.955316        13.796262
26   7.532887       14.413598        13.405007
27   7.210760       12.786455        35.318381
28   6.605152       18.264556        11.814820
29   6.560548       15.303206        10.713838
30   6.199448       11.564128         9.113124
31   6.113638       15.270192         8.821823
32   6.340886       12.921961         4.608525
33   5.549395       10.305749        21.463481
34   4.642607       15.769392        21.079767
35   4.601402        8.504744        20.551764
36   2.866376       12.705621        20.112682
37   4.406995        5.128314        19.702942
38   2.022959        6.594793        18.526510
39   3.855851        8.298209        17.499930
40   2.875433       11.854605        17.279567
41   2.789292        8.471077        16.447071
42   2.364093        9.618963        14.800111
43   1.550573       12.738230         3.553417
44   2.217774       15.480614         2.833472
45   0.100023       12.415304         0.190393
46   0.131546       11.581621        29.711446
47   0.000000       13.542692         0.000000
48   0.054205        5.174315         0.000000
49   0.000000       11.698380        21.440983

In [ ]:
# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[0:4,0:2]
X

   R&D Spend  Administration
0  16.534920       13.689780
1  15.680000       15.137759
2  15.344151       10.114555
3  14.437241       11.380000

In [ ]:
y = df1.iloc[0:4,-1]
y

0    47.178410
1    44.389853
2    40.793454
3    38.319962
Name: Marketing Spend, dtype: float64

In [ ]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[4,0:2].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([36.28976674])

In [ ]:
df1.iloc[4,-1] = 36.28

In [ ]:
df1

    R&D Spend  Administration  Marketing Spend
0   16.534920       13.689780        47.178410
1   15.680000       15.137759        44.389853
2   15.344151       10.114555        40.793454
3   14.437241       11.380000        38.319962
4   14.210734        9.139177        36.280000
5   13.187690        9.981471        36.286136
6   13.461546       14.719887        12.771682
7   13.029813       14.553006        32.387668
8   12.054252       14.871895        31.161329
9   12.333488       10.867917        30.498162
10  10.191308       11.059411        22.916095
11  10.067196        9.179061        24.974455
12   9.386375       12.732038        24.983944
13   9.199239       13.549507        25.266493
14  11.994324       15.654742        25.651292
15  11.452361       12.261684        26.177623
16   7.801311       12.159755        26.434606
17   9.465716       14.507758        28.257431
18   9.174916       11.417579        29.491957
19   8.641970       15.351411         0.000000
20   7.625386       11.386730        29.866447
21   7.838947       15.377343        29.973729
22   7.399456       12.278275        30.331926
23   6.753253       10.575103        30.476873
24   7.704401        9.928134        14.057481
25   6.466471       13.955316        13.796262
26   7.532887       14.413598        13.405007
27   7.210760       12.786455        35.318381
28   6.605152       18.264556        11.814820
29   6.560548       15.303206        10.713838
30   6.199448       11.564128         9.113124
31   6.113638       15.270192         8.821823
32   6.340886       12.921961         4.608525
33   5.549395       10.305749        21.463481
34   4.642607       15.769392        21.079767
35   4.601402        8.504744        20.551764
36   2.866376       12.705621        20.112682
37   4.406995        5.128314        19.702942
38   2.022959        6.594793        18.526510
39   3.855851        8.298209        17.499930
40   2.875433       11.854605        17.279567
41   2.789292        8.471077        16.447071
42   2.364093        9.618963        14.800111
43   1.550573       12.738230         3.553417
44   2.217774       15.480614         2.833472
45   0.100023       12.415304         0.190393
46   0.131546       11.581621        29.711446
47   0.000000       13.542692         0.000000
48   0.054205        5.174315         0.000000
49   0.000000       11.698380        21.440983

In [ ]:
# Subtract 0th iteration from 1st iteration

df1 - df0

    R&D Spend  Administration  Marketing Spend
0    0.000000        0.000000         0.000000
1    8.489218        0.000000         0.000000
2    0.000000        0.000000         0.000000
3    0.000000       -0.759919         0.000000
4    0.000000        0.000000        -0.336842
5    0.000000        0.000000         0.000000
6    0.000000        0.000000         0.000000
7    0.000000        0.000000         0.000000
8    0.000000        0.000000         0.000000
9    0.000000        0.000000         0.000000
10   0.000000        0.000000         0.000000
11   0.000000        0.000000         0.000000
12   0.000000        0.000000         0.000000
13   0.000000        0.000000         0.000000
14   0.000000        0.000000         0.000000
15   0.000000        0.000000         0.000000
16   0.000000        0.000000         0.000000
17   0.000000        0.000000         0.000000
18   0.000000        0.000000         0.000000
19   0.000000        0.000000         0.000000
20   0.000000        0.000000         0.000000
21   0.000000        0.000000         0.000000
22   0.000000        0.000000         0.000000
23   0.000000        0.000000         0.000000
24   0.000000        0.000000         0.000000
25   0.000000        0.000000         0.000000
26   0.000000        0.000000         0.000000
27   0.000000        0.000000         0.000000
28   0.000000        0.000000         0.000000
29   0.000000        0.000000         0.000000
30   0.000000        0.000000         0.000000
31   0.000000        0.000000         0.000000
32   0.000000        0.000000         0.000000
33   0.000000        0.000000         0.000000
34   0.000000        0.000000         0.000000
35   0.000000        0.000000         0.000000
36   0.000000        0.000000         0.000000
37   0.000000        0.000000         0.000000
38   0.000000        0.000000         0.000000
39   0.000000        0.000000         0.000000
40   0.000000        0.000000         0.000000
41   0.000000        0.000000         0.000000
42   0.000000        0.000000         0.000000
43   0.000000        0.000000         0.000000
44   0.000000        0.000000         0.000000
45   0.000000        0.000000         0.000000
46   0.000000        0.000000         0.000000
47   0.000000        0.000000         0.000000
48   0.000000        0.000000         0.000000
49   0.000000        0.000000         0.000000

In [ ]:
df2 = df1.copy()

df2.iloc[1,0] = np.nan

df2

    R&D Spend  Administration  Marketing Spend
0   16.534920       13.689780        47.178410
1         NaN       15.137759        44.389853
2   15.344151       10.114555        40.793454
3   14.437241       11.380000        38.319962
4   14.210734        9.139177        36.280000
5   13.187690        9.981471        36.286136
6   13.461546       14.719887        12.771682
7   13.029813       14.553006        32.387668
8   12.054252       14.871895        31.161329
9   12.333488       10.867917        30.498162
10  10.191308       11.059411        22.916095
11  10.067196        9.179061        24.974455
12   9.386375       12.732038        24.983944
13   9.199239       13.549507        25.266493
14  11.994324       15.654742        25.651292
15  11.452361       12.261684        26.177623
16   7.801311       12.159755        26.434606
17   9.465716       14.507758        28.257431
18   9.174916       11.417579        29.491957
19   8.641970       15.351411         0.000000
20   7.625386       11.386730        29.866447
21   7.838947       15.377343        29.973729
22   7.399456       12.278275        30.331926
23   6.753253       10.575103        30.476873
24   7.704401        9.928134        14.057481
25   6.466471       13.955316        13.796262
26   7.532887       14.413598        13.405007
27   7.210760       12.786455        35.318381
28   6.605152       18.264556        11.814820
29   6.560548       15.303206        10.713838
30   6.199448       11.564128         9.113124
31   6.113638       15.270192         8.821823
32   6.340886       12.921961         4.608525
33   5.549395       10.305749        21.463481
34   4.642607       15.769392        21.079767
35   4.601402        8.504744        20.551764
36   2.866376       12.705621        20.112682
37   4.406995        5.128314        19.702942
38   2.022959        6.594793        18.526510
39   3.855851        8.298209        17.499930
40   2.875433       11.854605        17.279567
41   2.789292        8.471077        16.447071
42   2.364093        9.618963        14.800111
43   1.550573       12.738230         3.553417
44   2.217774       15.480614         2.833472
45   0.100023       12.415304         0.190393
46   0.131546       11.581621        29.711446
47   0.000000       13.542692         0.000000
48   0.054205        5.174315         0.000000
49   0.000000       11.698380        21.440983

In [ ]:
X = df2.iloc[[0,2,3,4],1:3]
y = df2.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[1,1:].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([15.5197258])

In [ ]:
df2.iloc[1,0] = 15.51

In [ ]:
df2.iloc[3,1] = np.nan
X = df2.iloc[[0,1,2,4],[0,2]]
y = df2.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([11.26664741])

In [ ]:
df2.iloc[3,1] = 11.26

In [ ]:
df2.iloc[4,-1] = np.nan

X = df2.iloc[0:4,0:2]
y = df2.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[4,0:2].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([36.22942274])

In [ ]:
df2.iloc[4,-1] = 36.22

In [ ]:
df2

    R&D Spend  Administration  Marketing Spend
0   16.534920       13.689780        47.178410
1   15.510000       15.137759        44.389853
2   15.344151       10.114555        40.793454
3   14.437241       11.260000        38.319962
4   14.210734        9.139177        36.220000
5   13.187690        9.981471        36.286136
6   13.461546       14.719887        12.771682
7   13.029813       14.553006        32.387668
8   12.054252       14.871895        31.161329
9   12.333488       10.867917        30.498162
10  10.191308       11.059411        22.916095
11  10.067196        9.179061        24.974455
12   9.386375       12.732038        24.983944
13   9.199239       13.549507        25.266493
14  11.994324       15.654742        25.651292
15  11.452361       12.261684        26.177623
16   7.801311       12.159755        26.434606
17   9.465716       14.507758        28.257431
18   9.174916       11.417579        29.491957
19   8.641970       15.351411         0.000000
20   7.625386       11.386730        29.866447
21   7.838947       15.377343        29.973729
22   7.399456       12.278275        30.331926
23   6.753253       10.575103        30.476873
24   7.704401        9.928134        14.057481
25   6.466471       13.955316        13.796262
26   7.532887       14.413598        13.405007
27   7.210760       12.786455        35.318381
28   6.605152       18.264556        11.814820
29   6.560548       15.303206        10.713838
30   6.199448       11.564128         9.113124
31   6.113638       15.270192         8.821823
32   6.340886       12.921961         4.608525
33   5.549395       10.305749        21.463481
34   4.642607       15.769392        21.079767
35   4.601402        8.504744        20.551764
36   2.866376       12.705621        20.112682
37   4.406995        5.128314        19.702942
38   2.022959        6.594793        18.526510
39   3.855851        8.298209        17.499930
40   2.875433       11.854605        17.279567
41   2.789292        8.471077        16.447071
42   2.364093        9.618963        14.800111
43   1.550573       12.738230         3.553417
44   2.217774       15.480614         2.833472
45   0.100023       12.415304         0.190393
46   0.131546       11.581621        29.711446
47   0.000000       13.542692         0.000000
48   0.054205        5.174315         0.000000
49   0.000000       11.698380        21.440983

In [ ]:
df2 - df1

    R&D Spend  Administration  Marketing Spend
0        0.00            0.00             0.00
1       -0.17            0.00             0.00
2        0.00            0.00             0.00
3        0.00           -0.12             0.00
4        0.00            0.00            -0.06
5        0.00            0.00             0.00
6        0.00            0.00             0.00
7        0.00            0.00             0.00
8        0.00            0.00             0.00
9        0.00            0.00             0.00
10       0.00            0.00             0.00
11       0.00            0.00             0.00
12       0.00            0.00             0.00
13       0.00            0.00             0.00
14       0.00            0.00             0.00
15       0.00            0.00             0.00
16       0.00            0.00             0.00
17       0.00            0.00             0.00
18       0.00            0.00             0.00
19       0.00            0.00             0.00
20       0.00            0.00             0.00
21       0.00            0.00             0.00
22       0.00            0.00             0.00
23       0.00            0.00             0.00
24       0.00            0.00             0.00
25       0.00            0.00             0.00
26       0.00            0.00             0.00
27       0.00            0.00             0.00
28       0.00            0.00             0.00
29       0.00            0.00             0.00
30       0.00            0.00             0.00
31       0.00            0.00             0.00
32       0.00            0.00             0.00
33       0.00            0.00             0.00
34       0.00            0.00             0.00
35       0.00            0.00             0.00
36       0.00            0.00             0.00
37       0.00            0.00             0.00
38       0.00            0.00             0.00
39       0.00            0.00             0.00
40       0.00            0.00             0.00
41       0.00            0.00             0.00
42       0.00            0.00             0.00
43       0.00            0.00             0.00
44       0.00            0.00             0.00
45       0.00            0.00             0.00
46       0.00            0.00             0.00
47       0.00            0.00             0.00
48       0.00            0.00             0.00
49       0.00            0.00             0.00

In [ ]:
df3 = df2.copy()

df3.iloc[1,0] = np.nan

df3

    R&D Spend  Administration  Marketing Spend
0   16.534920       13.689780        47.178410
1         NaN       15.137759        44.389853
2   15.344151       10.114555        40.793454
3   14.437241       11.260000        38.319962
4   14.210734        9.139177        36.220000
5   13.187690        9.981471        36.286136
6   13.461546       14.719887        12.771682
7   13.029813       14.553006        32.387668
8   12.054252       14.871895        31.161329
9   12.333488       10.867917        30.498162
10  10.191308       11.059411        22.916095
11  10.067196        9.179061        24.974455
12   9.386375       12.732038        24.983944
13   9.199239       13.549507        25.266493
14  11.994324       15.654742        25.651292
15  11.452361       12.261684        26.177623
16   7.801311       12.159755        26.434606
17   9.465716       14.507758        28.257431
18   9.174916       11.417579        29.491957
19   8.641970       15.351411         0.000000
20   7.625386       11.386730        29.866447
21   7.838947       15.377343        29.973729
22   7.399456       12.278275        30.331926
23   6.753253       10.575103        30.476873
24   7.704401        9.928134        14.057481
25   6.466471       13.955316        13.796262
26   7.532887       14.413598        13.405007
27   7.210760       12.786455        35.318381
28   6.605152       18.264556        11.814820
29   6.560548       15.303206        10.713838
30   6.199448       11.564128         9.113124
31   6.113638       15.270192         8.821823
32   6.340886       12.921961         4.608525
33   5.549395       10.305749        21.463481
34   4.642607       15.769392        21.079767
35   4.601402        8.504744        20.551764
36   2.866376       12.705621        20.112682
37   4.406995        5.128314        19.702942
38   2.022959        6.594793        18.526510
39   3.855851        8.298209        17.499930
40   2.875433       11.854605        17.279567
41   2.789292        8.471077        16.447071
42   2.364093        9.618963        14.800111
43   1.550573       12.738230         3.553417
44   2.217774       15.480614         2.833472
45   0.100023       12.415304         0.190393
46   0.131546       11.581621        29.711446
47   0.000000       13.542692         0.000000
48   0.054205        5.174315         0.000000
49   0.000000       11.698380        21.440983

In [ ]:
X = df3.iloc[[0,2,3,4],1:3]
y = df3.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[1,1:].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([15.48532879])

In [ ]:
df3.iloc[1,0] = 15.48

In [ ]:

df3.iloc[3,1] = np.nan
X = df3.iloc[[0,1,2,4],[0,2]]
y = df3.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[3,[0,2]].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([11.24138486])

In [ ]:
df3.iloc[3,1] = 11.24

In [ ]:
df3.iloc[4,-1] = np.nan

X = df3.iloc[0:4,0:2]
y = df3.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[4,0:2].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([36.22294123])

In [ ]:
df3.iloc[4,-1] = 36.22

In [ ]:
df2.iloc[3,1] = 11.24

In [ ]:
df3

    R&D Spend  Administration  Marketing Spend
0   16.534920       13.689780        47.178410
1   15.480000       15.137759        44.389853
2   15.344151       10.114555        40.793454
3   14.437241       11.240000        38.319962
4   14.210734        9.139177        36.220000
5   13.187690        9.981471        36.286136
6   13.461546       14.719887        12.771682
7   13.029813       14.553006        32.387668
8   12.054252       14.871895        31.161329
9   12.333488       10.867917        30.498162
10  10.191308       11.059411        22.916095
11  10.067196        9.179061        24.974455
12   9.386375       12.732038        24.983944
13   9.199239       13.549507        25.266493
14  11.994324       15.654742        25.651292
15  11.452361       12.261684        26.177623
16   7.801311       12.159755        26.434606
17   9.465716       14.507758        28.257431
18   9.174916       11.417579        29.491957
19   8.641970       15.351411         0.000000
20   7.625386       11.386730        29.866447
21   7.838947       15.377343        29.973729
22   7.399456       12.278275        30.331926
23   6.753253       10.575103        30.476873
24   7.704401        9.928134        14.057481
25   6.466471       13.955316        13.796262
26   7.532887       14.413598        13.405007
27   7.210760       12.786455        35.318381
28   6.605152       18.264556        11.814820
29   6.560548       15.303206        10.713838
30   6.199448       11.564128         9.113124
31   6.113638       15.270192         8.821823
32   6.340886       12.921961         4.608525
33   5.549395       10.305749        21.463481
34   4.642607       15.769392        21.079767
35   4.601402        8.504744        20.551764
36   2.866376       12.705621        20.112682
37   4.406995        5.128314        19.702942
38   2.022959        6.594793        18.526510
39   3.855851        8.298209        17.499930
40   2.875433       11.854605        17.279567
41   2.789292        8.471077        16.447071
42   2.364093        9.618963        14.800111
43   1.550573       12.738230         3.553417
44   2.217774       15.480614         2.833472
45   0.100023       12.415304         0.190393
46   0.131546       11.581621        29.711446
47   0.000000       13.542692         0.000000
48   0.054205        5.174315         0.000000
49   0.000000       11.698380        21.440983

In [ ]:
df3 - df2

    R&D Spend  Administration  Marketing Spend
0        0.00             0.0              0.0
1       -0.03             0.0              0.0
2        0.00             0.0              0.0
3        0.00             0.0              0.0
4        0.00             0.0              0.0
5        0.00             0.0              0.0
6        0.00             0.0              0.0
7        0.00             0.0              0.0
8        0.00             0.0              0.0
9        0.00             0.0              0.0
10       0.00             0.0              0.0
11       0.00             0.0              0.0
12       0.00             0.0              0.0
13       0.00             0.0              0.0
14       0.00             0.0              0.0
15       0.00             0.0              0.0
16       0.00             0.0              0.0
17       0.00             0.0              0.0
18       0.00             0.0              0.0
19       0.00             0.0              0.0
20       0.00             0.0              0.0
21       0.00             0.0              0.0
22       0.00             0.0              0.0
23       0.00             0.0              0.0
24       0.00             0.0              0.0
25       0.00             0.0              0.0
26       0.00             0.0              0.0
27       0.00             0.0              0.0
28       0.00             0.0              0.0
29       0.00             0.0              0.0
30       0.00             0.0              0.0
31       0.00             0.0              0.0
32       0.00             0.0              0.0
33       0.00             0.0              0.0
34       0.00             0.0              0.0
35       0.00             0.0              0.0
36       0.00             0.0              0.0
37       0.00             0.0              0.0
38       0.00             0.0              0.0
39       0.00             0.0              0.0
40       0.00             0.0              0.0
41       0.00             0.0              0.0
42       0.00             0.0              0.0
43       0.00             0.0              0.0
44       0.00             0.0              0.0
45       0.00             0.0              0.0
46       0.00             0.0              0.0
47       0.00             0.0              0.0
48       0.00             0.0              0.0
49       0.00             0.0              0.0